name: Run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - run: mkdir build
      - run: ls
      - run: cd build
      - run: cmake ..
      - run: make
      - run: ./mytests
