name: Run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: cmake .
      - run: make
      - run: ./mytests
